version: '3'
services:
  web:
    build: .
    image: web-app:latest
    ports:
      - "8080:8080"
    environment:
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
